apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: LoadBalancer # Use NodeNodePort if LoadBalancer isn't working
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000  # Match with containerPort